check ```BaseGeometry class```
"""
 Test class BaseGeometry with methods.
- Public instance method: def area(self): that raises an Exception with the message area() is not implemented
- Public instance method: def integer_validator(self, name, value): that validates value:
- you can assume name is always a string
- if value is not an integer: raise a TypeError exception, with the message <name> must be an integer
- if value is less or equal to 0: raise a ValueError exception with the message <name> must be greater than 0
- You are not allowed to import any module
"""
-----------------------
Checking docstring mod:
    >>> __import__('7-base_geometry').__doc__ != None
    True

Import the class:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

check class docstring:

    >>> BaseGeometry.__doc__ != None
    True

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("num", 10)
    >>> bg.integer_validator("width", 98)
    >>> bg.integer_validator("int", "7")
    Traceback (most recent call last):
    ...
    TypeError: int must be an integer

    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

    >>> bg.integer_validator("my_num", "Dav")
    Traceback (most recent call last):
    ...
    TypeError: my_num must be an integer

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ...
    ValueError: age must be greater than 0

    >>> bg.integer_validator("distance", -10)
    Traceback (most recent call last):
    ...
    ValueError: distance must be greater than 0

    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

    >>> bg.integer_validator("Dav", 5)

    >>> bg.integer_validator("date", (5,))
    Traceback (most recent call last):
    ...
    TypeError: date must be an integer

    >>> bg.integer_validator("date", [5])
    Traceback (most recent call last):
    ...
    TypeError: date must be an integer

    >>> bg.integer_validator("int", 'D')
    Traceback (most recent call last):
    ...
    TypeError: int must be an integer

    >>> bg.integer_validator("int", 13.2)
    Traceback (most recent call last):
    ...
    TypeError: int must be an integer

    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg.integer_validator("my_num", -7)
    Traceback (most recent call last):
    ...
    ValueError: my_num must be greater than 0

    >>> bg.integer_validator("my_num", (9,))
    Traceback (most recent call last):
    ...
    TypeError: my_num must be an integer

    >>> bg.integer_validator("my_num", [8])
    Traceback (most recent call last):
    ...
    TypeError: my_num must be an integer

    >>> bg.integer_validator("my_num", True)
    Traceback (most recent call last):
    ...
    TypeError: my_num must be an integer

    >>> bg.integer_validator("my_num", {1, 2})
    Traceback (most recent call last):
    ...
    TypeError: my_num must be an integer

    >>> bg.integer_validator("date", None)
    Traceback (most recent call last):
    ...
    TypeError: date must be an integer

    >>> bg.integer_validator("date", {1,2})
    Traceback (most recent call last):
    ...
    TypeError: date must be an integer